chore: fix contrainer extend example
sapphiredev/pieces pull request #183
Opened 2022-04-09 17:50 UTC by r-priyam

Current example explains how to inject the `client` property in container which is invalid because it's already available in `container`. Replaced it with simple example to not create confusion.

2022-04-09 18:00 UTC, Lioness100 commented
Is the client class needed/relevant?

2022-04-09 18:01 UTC, r-priyam commented
> Is the client class needed/relevant?

Not really but since it was there before, I just fixed it. It can be done without it too, agreed

2022-04-10 06:16 UTC, kyranet commented
I do not agree with the changes being made here, it's supposed to show a practical example of extending /pieces's container, and has no relationship with /framework.

2022-04-10 06:21 UTC, r-priyam commented
> I do not agree with the changes being made here, it's supposed to show a practical example of extending /pieces's container, and has no relationship with /framework.

@kyranet would this be ok then?
```ts
import { container } from '@sapphire/pieces';

conatiner.version = '...';
```

2022-04-10 08:05 UTC, favna requested changes
Kyra just means that you shouldn't modify the library

2022-04-10 08:05 UTC, favna commented on src/lib/shared/Container.ts
> + * import { container } from '@sapphire/framework';
```suggestion
 * import { container } from '@sapphire/pieces';
```

2022-04-10 16:23 UTC, favna approved these changes

2022-04-10 17:43 UTC, kyranet approved these changes

2022-04-10 17:49 UTC, vladfrangu approved these changes

2022-04-10 18:17 UTC, merged