feat: add URL support for register methods
sapphiredev/pieces pull request #231
Opened 2022-08-02 08:33 UTC by kyranet

This way, URLs can be used without calling `fileURLToPath`.

2022-08-02 11:10 UTC, vladfrangu submitted a review, later dismissed

2022-08-02 11:10 UTC, vladfrangu commented on src/lib/internal/Path.ts
> +import { fileURLToPath } from 'url';
Use node: import protocol

2022-08-02 12:22 UTC, kyranet commented on src/lib/internal/Path.ts
> +import { fileURLToPath } from 'url';
```suggestion
import { fileURLToPath } from 'node:url';
```

2022-08-02 17:34 UTC, favna requested changes

2022-08-02 17:34 UTC, favna commented on src/lib/internal/Path.ts
> +export type Path = string | URL;
Use `PathLike` from `node:fs`

```ts
import type { PathLike } from 'node:fs'
```

2022-08-02 23:21 UTC, kyranet commented on src/lib/internal/Path.ts
> +export type Path = string | URL;
PathLike includes Buffer, which there isn't an easy way to transform to string.

2022-08-03 06:19 UTC, favna commented on src/lib/internal/Path.ts
> +export type Path = string | URL;
I guess

2022-08-03 06:20 UTC, favna approved these changes

2022-08-03 06:21 UTC, vladfrangu approved these changes

2022-08-04 22:31 UTC, merged