feat(StoreRegistry): add queue and virtual file support
sapphiredev/pieces pull request #344
Opened 2023-11-12 14:46 UTC by kyranet

Adds a new method, `container.stores.loadPiece()`, which loads or queues a piece into the piece registries. Useful
specially for running Sapphire bots in environments where FS is limited or unavailable.

2023-11-12 14:54 UTC, vladfrangu commented on src/lib/structures/StoreRegistry.ts
> +		this.#calledLoad = true;
Don't want to check if calledLoad is called again?

2023-11-12 14:55 UTC, kyranet commented on src/lib/structures/StoreRegistry.ts
> +		this.#calledLoad = true;
For which purpose? The queue is empty after loading, after all.

2023-11-12 14:57 UTC, vladfrangu requested changes

2023-11-12 14:57 UTC, vladfrangu commented on src/lib/structures/StoreRegistry.ts
> +		// Load from FS
Isn't this still unusable outside fs-accessible systems? We need to make it opt-in or something

2023-11-12 15:02 UTC, kyranet commented on src/lib/structures/StoreRegistry.ts
> +		// Load from FS
If `Store#paths` is empty (and it will provided that core and plugin libraries are updated), no FS operation is done:
https://github.com/sapphiredev/pieces/blob/62159e1a638ad7a9779c4c9b1c6faaa021f834c3/src/lib/structures/Store.ts#L161-L165

As for the user, they'll have to pass `baseUserDirectory: null` in the `SapphireClientOptions`, and it's documented as such:
https://github.com/sapphiredev/framework/blob/d58810f76676184061e775e6249a4d01bdde67c3/src/lib/SapphireClient.ts#L33-L40
The default behaviour isn't applied if it's set to `null` too:
https://github.com/sapphiredev/framework/blob/d58810f76676184061e775e6249a4d01bdde67c3/src/lib/SapphireClient.ts#L335-L338

The combination of the two parts can make FS completely optional.

2023-11-12 15:03 UTC, vladfrangu submitted a review, later dismissed

2023-11-13 19:48 UTC, favna commented on src/lib/structures/StoreRegistry.ts
> +		// Load from FS
How would the user apply this option when only using @sapphire/pieces and not @sapphire/framework? i.e. making @skyra/http-framework serverless compatible (something that is very much desirable for HTTP only bots!)

2023-11-13 19:48 UTC, favna commented on src/lib/structures/StoreRegistry.ts
> +	#calledLoad = false;
Weren't you (@kyranet) and @vladfrangu saying private fields are still a perf impact?

2023-11-13 19:53 UTC, favna requested changes

2023-11-13 19:53 UTC, favna commented on src/lib/structures/StoreRegistry.ts
> +	 * - This method is useful in environments where FS access is limited or unavailable, such as serverless.
```suggestion
	 * - This method is useful in environments where file system access is limited or unavailable, such as when using
	 * 	 {@link https://en.wikipedia.org/wiki/Serverless_computing Serverless Computing}.
```

2023-11-13 22:38 UTC, kyranet commented on src/lib/structures/StoreRegistry.ts
> +		// Load from FS
Both `@sapphire/framework` and `@skyra/http-framework` have this bit:
```typescript
if (options.baseUserDirectory !== null) {
	container.stores.registerPath(options.baseUserDirectory);
}
```
Passing `baseUserDirectory: null` in both will disable FS on the user's side.

For users using `@sapphire/pieces` directly, they can skip the `container.stores.registerPath` call altogether. If no paths are registered (framework and plugins need to be updated for this to not register any), FS is skipped.

2023-11-13 22:42 UTC, kyranet commented on src/lib/structures/StoreRegistry.ts
> +	#calledLoad = false;
Not since Node.js v18, Vlad showed us a benchmark proving that, the performance is roughly the same as a regular field. That being said, performance here is a non-issue since this is, at most, called only once in runtime.

2023-11-14 06:53 UTC, vladfrangu commented on src/lib/structures/StoreRegistry.ts
> +		// Load from FS
> Serverless bots can use this new API to load their pieces without pieces, obviously they'll need to have a lot of imports so the files are loaded (and executed), but this makes it easier for bundlers to bundle all the code in one binary, as no FS calls are done to load the pieces. This is also what we'll have to do in `@sapphire/framework` and plugins to support serverless environments.

Can you open a PR for that too? Making all the core pieces virtual in sapphire should be enough right?

2023-11-14 06:54 UTC, vladfrangu approved these changes

2023-11-14 10:35 UTC, vladfrangu commented
Could we make the name a symbol too @kyranet? That way we can load core pieces with unique symbols and solve yet another issue: overriding with the same name

2023-11-15 09:44 UTC, kyranet commented
`Piece#name` and `PieceOptions#name` accepting `string | Symbol` will be a follow-up PR.

2023-11-15 13:35 UTC, favna approved these changes

2023-11-15 13:40 UTC, merged