fix(RootScan): fixed support for packages which only define module field i.e. through bun init
sapphiredev/pieces pull request #369
Opened 2023-12-22 09:46 UTC by favna

2023-12-22 09:48 UTC, vladfrangu approved these changes

2023-12-22 10:57 UTC, vladfrangu requested changes

2023-12-22 10:57 UTC, vladfrangu commented on tests/lib/internal/RootScan.test.ts
> +			expectRootDataToEqual(rootData, `${noTypeBasePath}/module/dist/lib`, 'CommonJS');
if it's module, it should be esm not CJS

2023-12-22 11:25 UTC, vladfrangu requested changes

2023-12-22 11:25 UTC, vladfrangu commented on src/lib/internal/RootScan.ts
> +			throw new Error(errorMessage);
The throw clauses are useless, as they will be swallowed by the catch block, lets either return the default object from the catch method or...idk

2023-12-22 11:25 UTC, vladfrangu commented on src/lib/internal/RootScan.ts
> +			if (module) return (data = { root: dirnameWithPath(cwd, module), type: 'CommonJS' });
Inline these in one call please that resolves root by module || main

2023-12-22 11:58 UTC, vladfrangu approved these changes

2023-12-23 20:36 UTC, favna commented
@sapphiredev pack

2023-12-24 15:21 UTC, kyranet requested changes

2023-12-24 15:21 UTC, kyranet commented on src/lib/internal/RootScan.ts
> + * Resets the root data cache.
This should be marked as `@private` or `@internal`, since it's not exported in the index file.

2023-12-24 15:21 UTC, kyranet commented on src/lib/internal/RootScan.ts
>  export function getRootData(): RootData {
We should have a separate function that returns `RootData` so this method becomes:
```ts
export function getRootData(): RootData {
	return (data ??= parseRootData());
}
```

This would allow us to do simple returns in the more complex function without having to remember to do `data =`, which reduces the function's complexity and makes it more resilient to changes in the future.

2023-12-24 15:21 UTC, kyranet commented on src/lib/internal/RootScan.ts
>  export function getRootData(): RootData {
Maybe with it, we could remove the new private `resetRootDataCache()` function, as it would parse, but it wouldn't cache.

2023-12-24 15:21 UTC, kyranet commented on tests/lib/internal/RootScan.test.ts
> +			mockCwd(`${commonJsBasePath}/main`);
This should use `join`, likewise everywhere else, and make the root a `resolve()`'d value available and used everywhere in this test, so `join(basePath, commonJsBasePath, 'main')`.

2023-12-24 15:21 UTC, kyranet commented on tests/lib/internal/RootScan.test.ts
> +		root: join(`tests/fixtures/${rootPath}`),
This is merely a `resolve` call (which is what `join` does in the background). However, it's best if we use `join`'s varargs instead.

2023-12-24 15:23 UTC, kyranet commented on tests/lib/internal/RootScan.test.ts
> +afterEach(() => {
Something I noticed after pressing the button... aren't `afterEach`s scoped by the `describe` they're in? Wouldn't this make it always check in all tests (future ones) rather than just `RootScan`'s?

2023-12-26 14:14 UTC, vladfrangu commented on tests/lib/internal/RootScan.test.ts
> +afterEach(() => {
Nop, it will only affect tests in this file

2023-12-27 12:25 UTC, vladfrangu approved these changes

2023-12-27 17:31 UTC, kyranet approved these changes

2023-12-27 22:42 UTC, merged